### ISSUE TITLE
FakePDB -> Generate .PDB file does not works for .DLL files

### ISSUE THREAD

**Issue by Mixaill** [Mixaill/FakePDB#12]
**Describe the bug**
FakePDB -> Generate .PDB file does not works for .DLL files

**To Reproduce**
1. Open .IDA project which is created from .dll file
2. Edit -> FakePDB -> Generate .PDB file
3. Only .json file is generated

**Additional context**
https://www.youtube.com/watch?v=5JYv7ynSxsM

**Comment by KingTerrytheTerrible** [comment]
i'm encountering this issue too, would be nice to have a fix for this, cheers

**Comment by Mixaill** [comment]
fixed in #14
