### ISSUE TITLE
Info on how to force load generated PDB's in WinDbg

### ISSUE THREAD

**Issue by p0358** [Mixaill/FakePDB#15]
I think it would be useful to link/mention/incorporate these methods (especially the latter one imo) somewhere in the readme, for people looking to make some use out of these PDBs:
http://ntcoder.com/bab/2012/03/06/how-to-force-symbol-loading-in-windbg/

**Comment by Mixaill** [comment]
Fixed in f62ff8d3978fe7455f7ed6aeb1b0da2e2de9e792
