### ISSUE TITLE
Switch to Github Actions

### ISSUE THREAD

**Issue by hacksysteam** [Mixaill/FakePDB#26]
**Is your feature request related to a problem? Please describe.**
AppVeyor is killing the build task as it exceeds 60 minutes of runtime.

**Describe the solution you'd like**
We should switch to Github Actions as it allows 6 hours of runtime. https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Mixaill** [comment]
Yeah, it is on my plan.
