### ISSUE TITLE
Build instruction

### ISSUE THREAD

**Issue by Mixaill** [Mixaill/FakePDB#3]
Easier compilation on both Windows and Linux, perhaps some specific instructions what packages are needed etc.

Requested in: https://twitter.com/j00ru/status/1176238005746634754

**Comment by saml1er** [comment]
I would really appreciate it if this issue gets resolved. I tried compiling with the latest version of LLVM, but I couldn't get it to work.
![Capture](https://user-images.githubusercontent.com/10183157/75825237-c64c0500-5dc6-11ea-826d-1bdda6b9d8f6.PNG)

**Comment by laomaiweng** [comment]
This looks like LLVM master. It got it to compile with LLVM 10.

**Comment by Mixaill** [comment]
Yeah, it is LLVM 10. Added info into readme.

**Comment by saml1er** [comment]
Thank you very much.
