### ISSUE TITLE
Is the Release still the latest version?

### ISSUE THREAD

**Issue by 1392081456** [Mixaill/FakePDB#39]
I saw that the code was updated 8 months ago. Do I need to Releasecompile it again? , emmmm  How can I compile it? I see a src for the plugin and a src for cpp。Should I compile the exe file from src_cpp and put it in the src_plugins/ida/fakepdb folder?

**Comment by Mixaill** [comment]
You can get the compiled version from the link in the readme

https://nightly.link/Mixaill/FakePDB/workflows/CI/master/binaries.zip

![image](https://github.com/user-attachments/assets/61624fa1-13b3-4cd2-bc19-5d9170f36c38)

**Comment by 1392081456** [comment]
> You can get the compiled version from the link in the readme
> 
> https://nightly.link/Mixaill/FakePDB/workflows/CI/master/binaries.zip
> 
> ![image](https://private-user-images.githubusercontent.com/704382/380642105-61624fa1-13b3-4cd2-bc19-5d9170f36c38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTc2NTMsIm5iZiI6MTczMDI5NzM1MywicGF0aCI6Ii83MDQzODIvMzgwNjQyMTA1LTYxNjI0ZmExLTEzYjMtNGNkMi1iYzE5LTVkOTE3MGYzNmMzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNDA5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjBhNmNiNzkzYTkxNGRhZTMyNzFlZTI4MTJmMWZjYWRjNDFiY2NhNGIwYTQ3YjJjMmM4MmUzN2M0ZGIzYjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.deI-PdpyUTOjGfH3tsr4tmNLc4l8D9nN54snfOTIGdU)

Thank!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   I hvae got it from the Download!
