### ISSUE TITLE
pe_debug website down, source available elsewhere?

### ISSUE THREAD

**Issue by gynt** [Mixaill/FakePDB#40]
**Describe the bug**
The link in the Readme to pe_debug is not working anymore.
Archive.org has a copy, but not of the source. Do you have the source code somewhere and can set up a GitHub mirror?
https://web.archive.org/web/20230416222304/http://pefrm-units.osdn.jp/pe_debug.html

**Comment by Mixaill** [comment]
@gynt https://github.com/svn2github/pefrm-units/tree/master/pe_debug
