### ISSUE TITLE
Some PDBs are shifted by 0x1000

### ISSUE THREAD

**Issue by Mixaill** [Mixaill/FakePDB#5]
The .pdbs I generated had addresses shifted by 0x1000. It looked like they should be relative to the image base instead of the section offset.

Requested in: https://twitter.com/j00ru/status/1176238722150555649

**Comment by Trass3r** [comment]
Should be fixed by https://github.com/Mixaill/FakePDB/commit/d779d3da28034ffed82038edfd8d6fa85bd77fc1

**Comment by Mixaill** [comment]
fixed
