### ISSUE TITLE
建议把依赖的LLVM文件也上传上来。

### ISSUE THREAD

**Issue by kouzhudong** [Mixaill/FakePDB#6]
LLVM太大了，光下载都半天，更不用说编译了。

有点遗憾：还没支持PE2+。

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mixaill** [comment]
>LLVM太大了，光下载都半天，更不用说编译了。
There is no plans to switch from LLVM at this moment.

>有点遗憾：还没支持PE2+。
PE32+ is tracked under #2
